# Week 8 (Tue) - Class Activities in CS 315

You are given the file `netflix_top10_countries.tsv` in the folder data, solve the following tasks using it.

**Table of Contents**

1. [Q1: Load the file](#q1)
2. [Q2: Show number of rows](#q2)
3. [Q3: Show column names](#q3)
4. [Q4: Show number of total countries](#q4)
5. [Q5: Show number of TV series](#q5)
6. [Q6: Number of TV series in South Korea](#q6)
7. [Q7: Total weeks of Squid Games in Italy ](#q7)
8. [Q8: Time frame for a given country](#q8)
9. [Q9: Is number of weeks in ranking equal?](#q9)
10. [Q10: Country with fewest weeks](#q10)

<a id="q1"></a>
### Q1: Load the file

In [2]:
import pandas as pd
url = "all-weeks-countries.tsv"
df = pd.read_csv(url, sep = '\t')
df.head()

,country_name,country_iso2,week,category,weekly_rank,show_title,season_title,cumulative_weeks_in_top_10
0,Argentina,AR,2026-10-18,Films,1,Therapy Done Right,NaN,1
1,Argentina,AR,2026-10-18,Films,2,Animals,NaN,2
2,Argentina,AR,2026-10-18,Films,3,Anyone But You,NaN,2
3,Argentina,AR,2026-10-18,Films,4,Doing Life,NaN,3
4,Argentina,AR,2026-10-18,Films,5,Ice Age: Collision Course,NaN,5

<a id="q2"></a>
### Q2: Show number of rows

In [3]:
df.shape[0]

515920

<a id="q3"></a>
### Q3: Show column names

In [4]:
df.columns

Index(['country_name', 'country_iso2', 'week', 'category', 'weekly_rank',
       'show_title', 'season_title', 'cumulative_weeks_in_top_10'],
      dtype='str')

<a id="q4"></a>
### Q4: Show number of total countries

In [5]:
df["country_name"].nunique()

94

<a id="q5"></a>
### Q5: Show number of TV series

In [6]:
df[df["category"]=="TV"]["show_title"].nunique()

3607

<a id="q6"></a>
### Q6: Number of TV series in South Korea

In [36]:
df[(df["country_name"]=="South Korea") &(df["category"]=="TV")]["show_title"].nunique()

486

<a id="q7"></a>
### Q7: Total weeks of Squid Game in Italy

In [7]:
len(df[(df["country_name"]=="Italy")&(df["show_title"]=="Squid Game")])

37

<a id="q8"></a>
### Q8: Time frame for a given country

Write a function that given a country name prints out the start and end date of their rankings.

Once you have created the function, call it for a few countries to test it.

In [8]:
def show_timeframe(df,country):
    x=df[df["country_name"]==country]
    start_date=x["week"].min()
    start_date=x["week"].max()
    print(f"Netflix rankings for {country} exist b/w {start_date}and {end_date}.")

<a id="q9"></a>
### Q9: Is number of weeks equal for each country?

The total number of weeks in the rankings is `len(df['week'].unique())`.

The total number of countries is `len(df['country_name'].unique())`.  

For every week, each country has 20 rows.   

If they all stayed the same number of weeks, then the product of these three weeks would be the same as the total number of rows.

In [9]:
len(df['week'].unique())*len(df['country_name'].unique())*20==len(df)

False

We should have expected this to be `False` since we saw in Q8 that Russia stopped being in the rankings after it attacked Ukraine in February 2022.

<a id="q10"></a>
### Q10: Country with fewest weeks

Write a one-liner that will show the country with the fewest weeks in the Netflix rankings

In [10]:
x = df.groupby('country_name')['week'].nunique().sort_values().index[0]

# rank2score

In [ ]:
def rank2score(rank):
    point = {1:25, 2: 18, 3: 15, 4: 12, 5: 10, 6:8, 7: 6, 8: 4, 9: 2, 10: 1}
    return point.get(rank, 0)

##### ^ had to put 0 after rank bc was getting a keyerror before

##### making score be based of my ranking function

In [12]:
df["score"] = df["weekly_rank"].apply(rank2score)

##### Guardian: The Lonely and Great God has one of the most famous and well-known soundtracks known for its music + sound

In [13]:

title = "Guardian: The Lonely and Great God"
showdf = df[df["show_title"] == title]

##### grouped the show's rows by country and calculated the sum of points. counted the total charting weeks and collected the weekly rankings into a list for each country.

##### also wanted to see, "ok yes how many total weeks but what were the rankings for all of those weeks"

In [15]:
mesh = showdf.groupby("country_name")
totalscore = mesh["score"].sum()
totalweeks = mesh["weekly_rank"].count()
rankingslist = mesh["weekly_rank"].apply(list)

##### adding all labels to df and npt forgetting to sort values @ end

In [16]:
summarydf = pd.DataFrame({"totalscore":totalscore, "totalweeks": totalweeks, "rankingslist": rankingslist,})
summarydf = summarydf.sort_values(by="totalscore",ascending=False)
summarydf

,totalscore,totalweeks,rankingslist
country_name,,,
South Korea,40,14,"[9, 10, 10, 8, 7, 6, 7, 10, 10, 10, 9, 9, 8, 10]"
Vietnam,37,9,"[8, 9, 9, 10, 9, 7, 5, 7, 8]"
Hong Kong,1,1,[10]